# plot_generator - Generated by AI Dev Assistant

library(ggplot2)

# Load the sales data
# Assuming the data file is in the same directory as the script
sales_data <- read.csv("sales_data.csv")

# Create a plot
plot <- ggplot(sales_data, aes(x = as.Date(date), y = sales)) +
  geom_line(color = "blue") +
  geom_point(color = "blue") +
  labs(title = "Sales Over Time", x = "Date", y = "Sales") +
  theme_minimal()

# Save the plot as a PNG file
ggsave("sales_plot.png", plot, width = 8, height = 6, units = "in")