# plot_generator - Generated by AI Dev Assistant

"""
Simple Python plot generator using matplotlib.
Reads sales_data.csv from the same directory and writes sales_plot.png.
"""

import os
import csv
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def generate_plot():
    csv_path = os.path.join(os.path.dirname(__file__), '..', '..', 'generated_apps/SalesDashboard', 'sales_data.csv')
    # If running from generated app, the CSV will be adjacent to this script; try fallback
    if not os.path.exists(csv_path):
        csv_path = os.path.join(os.path.dirname(__file__), '..', 'sales_data.csv')

    dates = []
    sales = []
    with open(csv_path, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            dates.append(row.get('date'))
            sales.append(float(row.get('sales') or 0))

    plt.figure(figsize=(8,4))
    plt.plot(dates, sales, marker='o')
    plt.title('Sales over Time')
    plt.xlabel('Date')
    plt.ylabel('Sales')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plot_path = os.path.join(os.path.dirname(__file__), '..', 'sales_plot.png')
    plt.savefig(plot_path)
    plt.close()

if __name__ == '__main__':
    generate_plot()